# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

###### Custom Options

# Containers have 2 CPUs by default. Speed up the build by using both.
# c.f. https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
env:
  global:
  - MAKEFLAGS="-j 2"
  - _R_CHECK_FORCE_SUGGESTS_=false

# Run R package on both release and developer versions
jobs:
  include:
  - r: release
  - r: devel
  - r: oldrel

# If one fails, avoid running the other.
matrix:
  fast_finish: true

# Enable coverage check on unit tests
after_success:
    - Rscript -e 'covr::codecov()'
